### ISSUE TITLE
Expose the version number of sqlite3

### ISSUE THREAD

**Issue by PaulKiddle** [fhellwig/sqlite-async#11]
Sometimes database consumers want to know exactly what version of sqlite they're dealing with. `node-sqlite3` has this available at `sqlite3.VERSION`, it would be useful to expose this info somewhere in sqlite-async too.

**Comment by fhellwig** [comment]
Since the sqlite-async module only exports the `Database` class, I added a static getter (`SQLITE3_VERSION`) that accomplishes your suggestion. I can't say I am proud of the way I did it (parsing the `package.json` file) but it does work. The `README` has been updated to document this and a test, which always passes, was added as well for completeness. (A higher fidelity test would also parse the `package.json` file and compare the strings but for now it just logs the version number to the console.)
